apm-server:
  host: "localhost:8200"
  rum:
    enabled: true

  kibana:
    enabled: true
    host: "http://kibana:5601"
    username: "elastic"
    password: "supertheo"

output.console:
  pretty: true
